### PR TITLE
merge docs with rewrite branch

### PR DESCRIPTION
**Pull request by Cats3153**
documentation for bot, context, command, and converter

### CODE REVIEW

**Comment by jay3332** [comment]
There are some methods that have been for whatever reason, deleted, if you can identify and re-add them, I can merge this request

**Comment by Cats3153** [comment]
okay 👌

**Comment by Cats3153** [comment]
accident

**Comment by Cats3153** [comment]
@jay3332 

> There are some methods that have been for whatever reason, deleted, if you can identify and re-add them, I can merge this request

merged the missing functions into the modified files 👌

**Comment by jay3332** [comment]
This is out of date :what:

**Comment by jay3332** [comment]
> This is out of date :what:

E.g. this still uses the old caching system

**Comment by Cats3153** [comment]
:blobpain: i'll just rewrite the whole thing 😔

**Comment by Cats3153** [comment]
I have pulled the rewrite branch into the docs branch, fixing some stuff rn

**Comment by jay3332** [comment]
Looks good to me.

**Comment by Cats3153** [comment]
:p thanks

**Pull request merged**
