### PR TITLE
use /gateway/bot and remove jay's betray

### PR DESCRIPTION
**Pull request by asze17**
\>:(((

### CODE REVIEW

**Comment by jay3332** [comment]
Looks pretty good to me, I'll merge this tomorrow (i want to refactor the code)

**Comment by asze17** [comment]
moment of jay the sus

**Comment by asze17** [comment]
image

**Comment by asze17** [comment]
angy angy

**Comment by asze17** [comment]
jay nono merge

**Comment by Cats3153** [comment]
smhsmh "This branch has conflicts that must be resolved"
also jay removed betray 👌

**Comment by asze17** [comment]
smh smh imagine making my code conflict

**Comment by asze17** [comment]
me make new because i no can resolve conflict sMH

**Pull request closed without merging**
